DEFAULT_RETRIEVAL_RESULTS = 10

PROGRESS_STAGE_ATOMIZER = "atomizer_finished"
PROGRESS_STAGE_BERT_PROGRESS = "bert_progress"
PROGRESS_STAGE_TOKEN_OCCLUSION_PROGRESS = "token_occlusion_progress"
PROGRESS_STAGE_TEXT_PATTERN = "text_pattern_finished"
PROGRESS_STAGE_TAVILY_NLI_PROGRESS = "tavily_nli_progress"
PROGRESS_STAGE_LLM_EVIDENCE_PROGRESS = "llm_evidence_progress"
PROGRESS_STAGE_FACT_CHECKING = "fact_checking_finished"
PROGRESS_STAGE_ANALYSIS = "analysis_finished"

NEUTRAL_SCORE = 0.5
VERDICT_BOUNDARIES = [0.25, 0.45, 0.65, 0.85]
BOUNDARY_MARGIN = 0.1
NEAR_NEUTRAL_WINDOW = 0.2
LARGE_STABILIZATION_DELTA = 0.2
SMALL_STABILIZATION_DELTA = 0.1
